site_name: "Première NSI - Lycée Edmond Michelet - Arpajon"
site_url: "https://nsimichelet91.github.io/1NSI/" 
#nav:
#  - 'accueil' : 'index.md'

theme:
  name: material
  site_url: ""
  custom_dir: docs/my_theme_customizations/
  font: false
  language: fr
  icon:
    logo: material/code-greater-than
    repo : fontawesome/brands/github
    admonition:
      note: fontawesome/solid/pen-to-square
  favicon: xtra/fav1NSI.png


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide
    - content.code.annotate 

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Mode clair


markdown_extensions:
  - meta
  - abbr
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      linenums: None
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎
      toc_depth: 3


plugins:
  - search
  - git-revision-date
  - awesome-pages:
      collapse_single_pages: false
  - macros
  

extra:
  social:
    - icon: fontawesome/solid/school
      link: http://www.lyc-michelet-arpajon.ac-versailles.fr/
      name: Lycée Edmond Michelet - Arpajon

extra_javascript:
  - xtra/javascripts/interpreter.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js

extra_css:
  - stylesheets/extra.css
  - xtra/stylesheets/pyoditeur.css


